import Head from 'next/head'
import classes from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={classes.userWelcome}>Hello user 23</h1>
      <ul>
        <li>
          <Link href={'portfolio'}>Portfolio</Link>
        </li>
        <li>
          <Link href={'clients'}>Clients</Link>
        </li>
      </ul>
    </>
  )
}
