import Head from 'next/head'
import classes from '@/styles/Home.module.css'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={classes.userWelcome}>Hello user 23</h1>
    </>
  )
}
