import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FormEvent, MutableRefObject, useRef, useState } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const emailInput = useRef() as MutableRefObject<HTMLInputElement>
  const feedbackInput = useRef() as MutableRefObject<HTMLTextAreaElement>
  const [feedbacks, setFeedbacks] = useState([])

  const submitFormHandler = (e: FormEvent) => {
    e.preventDefault()

    const email = emailInput.current?.value
    const feedback = feedbackInput.current?.value

    fetch('/api/feedback', {
      method: 'POST',
      body: JSON.stringify({
        email,
        feedback
      }),
      headers: {
        'Content-type': 'application/json'
      }
    }).then((response) => {
      return response.json()
    }).then((data) => {
      console.log(data)
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>Home page</h1>
        </div>
        <form onSubmit={submitFormHandler}>
          <div>
            <label htmlFor='email'>E-mail</label>
            <input type='email' name='email' ref={emailInput} />
          </div>
          <div>
            <label htmlFor='feedback'>Feedback</label>
            <textarea name='feedback' ref={feedbackInput}></textarea>
          </div>
          <button type='submit'>Submit feedback</button>
        </form>
        <hr />
        <Link href={'/feedback'}>Get feedbacks</Link>
      </main>
    </>
  )
}
