import Layout from '@/components/layout/layout'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NotificationContextProvider } from '@/store/notification-context'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationContextProvider>
          <Layout>
            {children}
          </Layout>
        </NotificationContextProvider>
        <div id="notifications"></div>
      </body>
    </html>
  )
}
